name = "Leaf Portfolio"
license = "WTFPL"
licenselink = "https://github.com/abowloflrf/hugo-leaf-portfolio/blob/master/LICENSE"
description = ""
homepage = "https://yetian.design/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "ruofeng"
  homepage = "https://ruofeng.me"
